# Welcome to Jekyll!
#

# Site settings
title: FVWM Wiki
email: jaimosskriletz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/wiki" # the subpath of your site, e.g. /blog
url: "http://fvwmforums.org" # the base hostname & protocol for your site
github_username: somiaj

# Build settings
markdown: kramdown
highlighter: none

kramdown:
  input: GFM
#  syntax_highlighter: rogue

exclude:
  - FvwmLexer/
  - Readme.md
